---
- hosts: all
  become: yes
  become_user: root
  vars:
    sdkman_script_install_url: http://get.sdkman.io
    sdkman_folder: '/home/vagrant/.sdkman'
    user_home_path: '/home/vagrant'
    gradle_version: 3.4
    grails_version: 2.5.5

  tasks:
  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest
  - name: install oracle jdk
    dnf:
      name: "java-1.8.0-openjdk-devel"
      state: present
  - name: add docker testing repo
    yum_repository:
      name: docker-testing
      description: docker testing repo
      baseurl: https://yum.dockerproject.org/repo/testing/fedora/$releasever/
      enabled: no
      gpgcheck: yes
      gpgkey: https://yum.dockerproject.org/gpg
  - name: install docker
    dnf:
      name: docker-engine
      state: present
      enablerepo: docker-testing
  - name: enable docker service
    service:
      name: docker
      state: started
      enabled: yes
  - name: git
    dnf:
      name: git-all
      state: present
  - name: nano
    dnf:
      name: nano
      state: present
  - name: vim
    dnf:
      name: vim
      state: present
  - name: Check if sdkman is installed
    shell: test -d {{sdkman_folder}} && echo "yes" || echo "no"
    register: is_sdkman_installed
  - name: unzip
    dnf:
      name: unzip
      state: present
  - name: zip
    dnf:
      name: zip
      state: present      
  - name: mlocate
    dnf:
      name: mlocate
      state: present
  - name: set sdkman installer permissions
    file:
      path: /vagrant/utils/sdkman-install.sh
      owner: vagrant
      group: vagrant
      mode: 0755
  - name: Install SDKMAN!
    when: is_sdkman_installed.stdout == "no"
    shell: /vagrant/utils/sdkman-install.sh
    become: no
  - name: Ensure presence of bashrc
    file: state=touch path={{user_home_path}}/.bashrc
    become: no
  - name: Add sdkman in .bashrc
    shell: echo "source {{sdkman_folder}}/bin/sdkman-init.sh" > {{user_home_path}}/.bashrc
    become: no
  - name: Execute sdkman init in current shell
    shell: source {{sdkman_folder}}/bin/sdkman-init.sh
    become: no
  - name: Installing gradle
    # This will read your bash profile file, which would setup sdkman-init.sh.
    command: bash -lc "sdk install gradle {{gradle_version}}"
    become: no
  - name: Installing gradle
    # This will read your bash profile file, which would setup sdkman-init.sh.
    command: bash -lc "sdk install grails {{grails_version}}"
    become: no